name: Convert Feed to CSV

on:
  push:
    branches:
      - master
    paths:
      - 'master-feed/**'

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Convert files to CSV
        run: |
          mkdir -p csv-output

          for file in master-feed/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              sed 's/|/,/g' "$file" > "csv-output/${filename%.*}.csv"
            fi
          done

      - name: Verify Output
        run: |
          ls -l csv-output

      - name: Commit CSV files
        run: |
          git config --global user.name "github-actions"
